src/objects/Bolletta__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bollette</relationshipLabel>
        <relationshipName>Bollette</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TypeGasLuce__c</fullName>
        <label>TypeGasLuce</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Gas</fullName>
                </value>
                <value>
                    <fullName>Luce</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/BatchGaseLuce.cls
global class BatchGaseLuce implements 
    Database.Batchable<sObject>, Database.Stateful {
    
        String str;
     global BatchGaseLuce(String typeBill) {
        this.str = typeBill;
    }   
        
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id,name FROM Account WHERE Id NOT In (SELECT Account__c FROM Bolletta__c)'
        );
    }
    global void execute(Database.BatchableContext bc, List<Account> scope){
        // process each batch of records
        List<Bolletta__c> bills = new List<Bolletta__c>();
        for (Account bl : scope) {
				Bolletta__c blt = new Bolletta__c(Account__c=bl.Id,name='Gianni',TypeGasLuce__c=str,price__c=666);
				// add contact to list to be updated
                bills.add(blt);
                // increment the instance member counter
                recordsProcessed = recordsProcessed + 1;   
        }
        insert bills;
    }    
    global void finish(Database.BatchableContext bc){
       
    }    
}