src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SetDiValori__c</fullName>
        <label>SetDiValori</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valore1</fullName>
                </value>
                <value>
                    <fullName>Valore2</fullName>
                </value>
                <value>
                    <fullName>Valore3</fullName>
                </value>
                <value>
                    <fullName>Valore4</fullName>
                </value>
                <value>
                    <fullName>Valore5</fullName>
                </value>
                <value>
                    <fullName>Valore6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/CMD_Case__mdt.object
<CustomObject>
    <fields>
        <fullName>CMD_Set__c</fullName>
        <label>CMD_Set</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valore1</fullName>
                    <default>true</default>
                    <label>Valore1</label>
                </value>
                <value>
                    <fullName>Valore2</fullName>
                </value>
                <value>
                    <fullName>Valore3</fullName>
                </value>
                <value>
                    <fullName>Valore4</fullName>
                </value>
                <value>
                    <fullName>Valore5</fullName>
                </value>
                <value>
                    <fullName>Valore6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/CMD_CaseTriggerClass.cls
public class CMD_CaseTriggerClass {
    
    public void assignmentCase(List<Case> cts){
        
        List<CMD_Case__mdt> cmds = [SELECT CMD_Set__c, UserName__c FROM CMD_Case__mdt];  
        Map<Id,CMD_Case__mdt> casemap = new Map<ID,CMD_Case__mdt>(cmds);
        System.debug('casemap.values --- >>>> '+casemap.values());
        SET<ID> keys = casemap.keyset();
        List<User> usr = [SELECT Name, id FROM user ];
        System.debug('set<id> - - - - - - > '+keys);
        //String s = 
        
        for(Case c : cts){
            for(CMD_Case__mdt cmd : casemap.values()){
                if(c.SetDiValori__c == cmd.CMD_Set__c){
                    for(User u : usr){
                        if(u.Name == cmd.UserName__c){ 
                            c.User__c = u.Id;
                        } 
                        /*else{ 
                       c.addError('User ' + cmd.UserName__c + ' does not exist');
                     } */
                    }
                  }
                         
            }            
        }         
    }  
}